
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A AUTH CON CONECTAR DESCONECTAR DESUSCRIBIRSE DISPOSITIVO ENCRIPTADO FALSE KEY MENSAJE MQTT PUBLICAR SUSCRIBIRSE TOPIC TRUE VALORprograma : comandoscomandos : comando\n                | comando comandoscomando : conectar\n               | desconectar\n               | publicar\n               | suscribirse\n               | desuscribirse\n               | habilitar_encriptado\n               | habilitar_authhabilitar_encriptado : ENCRIPTADO A valor_booleanovalor_booleano : TRUE\n                      | FALSEhabilitar_auth : AUTH VALOR VALORconectar : CONECTAR MQTT DISPOSITIVOdesconectar : DESCONECTAR MQTT DISPOSITIVOpublicar : PUBLICAR DISPOSITIVO MENSAJE A TOPIC CON KEY VALORsuscribirse : SUSCRIBIRSE A TOPICdesuscribirse : DESUSCRIBIRSE A TOPIC'
    
_lr_action_items = {'CONECTAR':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[11,11,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'DESCONECTAR':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[12,12,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'PUBLICAR':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[13,13,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'SUSCRIBIRSE':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[14,14,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'DESUSCRIBIRSE':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[15,15,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'ENCRIPTADO':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[16,16,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'AUTH':([0,3,4,5,6,7,8,9,10,26,27,29,30,31,32,33,34,39,],[17,17,-4,-5,-6,-7,-8,-9,-10,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'$end':([1,2,3,4,5,6,7,8,9,10,18,26,27,29,30,31,32,33,34,39,],[0,-1,-2,-4,-5,-6,-7,-8,-9,-10,-3,-15,-16,-18,-19,-11,-12,-13,-14,-17,]),'MQTT':([11,12,],[19,20,]),'DISPOSITIVO':([13,19,20,],[21,26,27,]),'A':([14,15,16,28,],[22,23,24,35,]),'VALOR':([17,25,38,],[25,34,39,]),'MENSAJE':([21,],[28,]),'TOPIC':([22,23,35,],[29,30,36,]),'TRUE':([24,],[32,]),'FALSE':([24,],[33,]),'CON':([36,],[37,]),'KEY':([37,],[38,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'comandos':([0,3,],[2,18,]),'comando':([0,3,],[3,3,]),'conectar':([0,3,],[4,4,]),'desconectar':([0,3,],[5,5,]),'publicar':([0,3,],[6,6,]),'suscribirse':([0,3,],[7,7,]),'desuscribirse':([0,3,],[8,8,]),'habilitar_encriptado':([0,3,],[9,9,]),'habilitar_auth':([0,3,],[10,10,]),'valor_booleano':([24,],[31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> comandos','programa',1,'p_programa','mqtt_parser.py',19),
  ('comandos -> comando','comandos',1,'p_comandos','mqtt_parser.py',23),
  ('comandos -> comando comandos','comandos',2,'p_comandos','mqtt_parser.py',24),
  ('comando -> conectar','comando',1,'p_comando','mqtt_parser.py',28),
  ('comando -> desconectar','comando',1,'p_comando','mqtt_parser.py',29),
  ('comando -> publicar','comando',1,'p_comando','mqtt_parser.py',30),
  ('comando -> suscribirse','comando',1,'p_comando','mqtt_parser.py',31),
  ('comando -> desuscribirse','comando',1,'p_comando','mqtt_parser.py',32),
  ('comando -> habilitar_encriptado','comando',1,'p_comando','mqtt_parser.py',33),
  ('comando -> habilitar_auth','comando',1,'p_comando','mqtt_parser.py',34),
  ('habilitar_encriptado -> ENCRIPTADO A valor_booleano','habilitar_encriptado',3,'p_habilitar_encriptado','mqtt_parser.py',37),
  ('valor_booleano -> TRUE','valor_booleano',1,'p_valor_booleano','mqtt_parser.py',43),
  ('valor_booleano -> FALSE','valor_booleano',1,'p_valor_booleano','mqtt_parser.py',44),
  ('habilitar_auth -> AUTH VALOR VALOR','habilitar_auth',3,'p_habilitar_auth','mqtt_parser.py',48),
  ('conectar -> CONECTAR MQTT DISPOSITIVO','conectar',3,'p_conectar','mqtt_parser.py',56),
  ('desconectar -> DESCONECTAR MQTT DISPOSITIVO','desconectar',3,'p_desconectar','mqtt_parser.py',66),
  ('publicar -> PUBLICAR DISPOSITIVO MENSAJE A TOPIC CON KEY VALOR','publicar',8,'p_publicar','mqtt_parser.py',75),
  ('suscribirse -> SUSCRIBIRSE A TOPIC','suscribirse',3,'p_suscribirse','mqtt_parser.py',100),
  ('desuscribirse -> DESUSCRIBIRSE A TOPIC','desuscribirse',3,'p_desuscribirse','mqtt_parser.py',107),
]
