
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A AUTH CON CONECTAR DESCONECTAR DESUSCRIBIRSE DISPOSITIVO ENCRIPTADO FALSE KEY MENSAJE MQTT NUMERO PUBLICAR QOS SUSCRIBIRSE TOPIC TRUE VALOR VALOR_STRINGprograma : comandoscomandos : comando\n               | comando comandoscomando : conectar\n              | desconectar\n              | publicar\n              | suscribirse\n              | desuscribirse\n              | habilitar_encriptado\n              | habilitar_auth\n              | establecer_qoshabilitar_encriptado : ENCRIPTADO A valor_booleanovalor_booleano : TRUE\n                     | FALSEhabilitar_auth : AUTH VALOR_STRING VALOR_STRINGestablecer_qos : QOS NUMEROconectar : CONECTAR MQTT DISPOSITIVOdesconectar : DESCONECTAR MQTT DISPOSITIVOpublicar : PUBLICAR MENSAJE A TOPIC CON KEY VALOR_STRINGsuscribirse : SUSCRIBIRSE A TOPICdesuscribirse : DESUSCRIBIRSE A TOPIC'
    
_lr_action_items = {'CONECTAR':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[12,12,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'DESCONECTAR':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[13,13,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'PUBLICAR':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[14,14,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'SUSCRIBIRSE':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[15,15,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'DESUSCRIBIRSE':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[16,16,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'ENCRIPTADO':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[17,17,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'AUTH':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[18,18,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'QOS':([0,3,4,5,6,7,8,9,10,11,28,29,30,32,33,34,35,36,37,41,],[19,19,-4,-5,-6,-7,-8,-9,-10,-11,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,20,28,29,30,32,33,34,35,36,37,41,],[0,-1,-2,-4,-5,-6,-7,-8,-9,-10,-11,-3,-16,-17,-18,-20,-21,-12,-13,-14,-15,-19,]),'MQTT':([12,13,],[21,22,]),'MENSAJE':([14,],[23,]),'A':([15,16,17,23,],[24,25,26,31,]),'VALOR_STRING':([18,27,40,],[27,37,41,]),'NUMERO':([19,],[28,]),'DISPOSITIVO':([21,22,],[29,30,]),'TOPIC':([24,25,31,],[32,33,38,]),'TRUE':([26,],[35,]),'FALSE':([26,],[36,]),'CON':([38,],[39,]),'KEY':([39,],[40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'comandos':([0,3,],[2,20,]),'comando':([0,3,],[3,3,]),'conectar':([0,3,],[4,4,]),'desconectar':([0,3,],[5,5,]),'publicar':([0,3,],[6,6,]),'suscribirse':([0,3,],[7,7,]),'desuscribirse':([0,3,],[8,8,]),'habilitar_encriptado':([0,3,],[9,9,]),'habilitar_auth':([0,3,],[10,10,]),'establecer_qos':([0,3,],[11,11,]),'valor_booleano':([26,],[34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> comandos','programa',1,'p_programa','mqtt_parser.py',18),
  ('comandos -> comando','comandos',1,'p_comandos','mqtt_parser.py',22),
  ('comandos -> comando comandos','comandos',2,'p_comandos','mqtt_parser.py',23),
  ('comando -> conectar','comando',1,'p_comando','mqtt_parser.py',27),
  ('comando -> desconectar','comando',1,'p_comando','mqtt_parser.py',28),
  ('comando -> publicar','comando',1,'p_comando','mqtt_parser.py',29),
  ('comando -> suscribirse','comando',1,'p_comando','mqtt_parser.py',30),
  ('comando -> desuscribirse','comando',1,'p_comando','mqtt_parser.py',31),
  ('comando -> habilitar_encriptado','comando',1,'p_comando','mqtt_parser.py',32),
  ('comando -> habilitar_auth','comando',1,'p_comando','mqtt_parser.py',33),
  ('comando -> establecer_qos','comando',1,'p_comando','mqtt_parser.py',34),
  ('habilitar_encriptado -> ENCRIPTADO A valor_booleano','habilitar_encriptado',3,'p_habilitar_encriptado','mqtt_parser.py',37),
  ('valor_booleano -> TRUE','valor_booleano',1,'p_valor_booleano','mqtt_parser.py',43),
  ('valor_booleano -> FALSE','valor_booleano',1,'p_valor_booleano','mqtt_parser.py',44),
  ('habilitar_auth -> AUTH VALOR_STRING VALOR_STRING','habilitar_auth',3,'p_habilitar_auth','mqtt_parser.py',48),
  ('establecer_qos -> QOS NUMERO','establecer_qos',2,'p_establecer_qos','mqtt_parser.py',56),
  ('conectar -> CONECTAR MQTT DISPOSITIVO','conectar',3,'p_conectar','mqtt_parser.py',62),
  ('desconectar -> DESCONECTAR MQTT DISPOSITIVO','desconectar',3,'p_desconectar','mqtt_parser.py',66),
  ('publicar -> PUBLICAR MENSAJE A TOPIC CON KEY VALOR_STRING','publicar',7,'p_publicar','mqtt_parser.py',70),
  ('suscribirse -> SUSCRIBIRSE A TOPIC','suscribirse',3,'p_suscribirse','mqtt_parser.py',90),
  ('desuscribirse -> DESUSCRIBIRSE A TOPIC','desuscribirse',3,'p_desuscribirse','mqtt_parser.py',97),
]
